### ISSUE TITLE
1.8.1.3 CRASH Caused by: java.lang.NullPointerException: Attempt to invoke virtual method android.media.MediaPlayer$OnCompletionListener on a null object reference

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RTFace_Login#33]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setOnCompletionListener(android.media.MediaPlayer$OnCompletionListener)' on a null object reference
        at com.example.iris.login1.GalleryActivity.setMeidaPlayerListeners(GalleryActivity.java:969)
        at com.example.iris.login1.GalleryActivity.initVarsOfMediaPlayer(GalleryActivity.java:487)
        at com.example.iris.login1.GalleryActivity.onCreate(GalleryActivity.java:317)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)

→ Note:  misspelling Meida is actually in GalleryActivity

**Comment by JackMostow** [comment]
@bhargavmyadam - Was this version 1.8.1.3?  On which branch?

**Comment by bhargavmyadam** [comment]
Yes professor it is 1.8.1.3.

**Comment by JackMostow** [comment]
Believe fixed.

**Comment by madeleinvillegas** [comment]
@rohankulkz please push the code changes
